# Generated by LLM

from __future__ import annotations

import datetime
import requests
from typing import (
    Any,
    Dict,
    Optional,
    Sequence,
    Union,
    Literal,
)

# =========================
# ENUMERATIONS (STRICT)
# =========================

LicenseCode = Literal[
    "cc-by",
    "cc-by-nc",
    "cc-by-nd",
    "cc-by-sa",
    "cc-by-nc-nd",
    "cc-by-nc-sa",
    "cc0",
]

Geoprivacy = Literal[
    "obscured",
    "obscured_private",
    "open",
    "private",
]

Obscuration = Literal[
    "obscured",
    "private",
    "none",
]

IconicTaxon = Literal[
    "Actinopterygii",
    "Animalia",
    "Amphibia",
    "Arachnida",
    "Aves",
    "Chromista",
    "Fungi",
    "Insecta",
    "Mammalia",
    "Mollusca",
    "Reptilia",
    "Plantae",
    "Protozoa",
    "unknown",
]

TaxonRank = Literal[
    "kingdom",
    "phylum",
    "subphylum",
    "superclass",
    "class",
    "subclass",
    "superorder",
    "order",
    "suborder",
    "infraorder",
    "superfamily",
    "epifamily",
    "family",
    "subfamily",
    "supertribe",
    "tribe",
    "subtribe",
    "genus",
    "genushybrid",
    "species",
    "hybrid",
    "subspecies",
    "variety",
    "form",
]

IdentificationFilter = Literal[
    "most_agree",
    "some_agree",
    "most_disagree",
]

QualityGrade = Literal[
    "casual",
    "needs_id",
    "research",
]

Order = Literal["asc", "desc"]

OrderBy = Literal[
    "created_at",
    "updated_at",
    "observed_on",
    "species_guess",
    "votes",
    "id",
    "random",
    "geo_score",
]

IUCNStatus = Literal[
    "LC",
    "NT",
    "VU",
    "EN",
    "CR",
    "EW",
    "EX",
]

# =========================
# INTERNAL SERIALIZER
# =========================

def _serialize(value: Any) -> Optional[str]:
    if value is None:
        return None
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (list, tuple, set)):
        return ",".join(str(v) for v in value)
    if isinstance(value, (datetime.date, datetime.datetime)):
        return value.isoformat()
    return str(value)

# =========================
# MAIN API FUNCTION
# =========================

def get_observations(
    *,
    acc: Optional[bool] = None,
    captive: Optional[bool] = None,
    endemic: Optional[bool] = None,
    geo: Optional[bool] = None,
    id_please: Optional[bool] = None,
    identified: Optional[bool] = None,
    introduced: Optional[bool] = None,
    mappable: Optional[bool] = None,
    native: Optional[bool] = None,
    out_of_range: Optional[bool] = None,
    pcid: Optional[bool] = None,
    photos: Optional[bool] = None,
    popular: Optional[bool] = None,
    sounds: Optional[bool] = None,
    taxon_is_active: Optional[bool] = None,
    threatened: Optional[bool] = None,
    verifiable: Optional[bool] = None,
    licensed: Optional[bool] = None,
    photo_licensed: Optional[bool] = None,
    expected_nearby: Optional[bool] = None,

    id: Optional[Sequence[int]] = None,
    not_id: Optional[Sequence[int]] = None,
    license: Optional[Sequence[LicenseCode]] = None,
    photo_license: Optional[Sequence[LicenseCode]] = None,
    sound_license: Optional[Sequence[LicenseCode]] = None,
    place_id: Optional[Sequence[int]] = None,
    project_id: Optional[Sequence[Union[int, str]]] = None,
    site_id: Optional[Sequence[int]] = None,
    taxon_id: Optional[Sequence[int]] = None,
    without_taxon_id: Optional[Sequence[int]] = None,
    taxon_name: Optional[Sequence[str]] = None,
    user_id: Optional[Sequence[Union[int, str]]] = None,
    user_login: Optional[Sequence[str]] = None,

    rank: Optional[Sequence[TaxonRank]] = None,
    hrank: Optional[TaxonRank] = None,
    lrank: Optional[TaxonRank] = None,
    iconic_taxa: Optional[Sequence[IconicTaxon]] = None,

    d1: Optional[datetime.date] = None,
    d2: Optional[datetime.date] = None,
    created_d1: Optional[datetime.datetime] = None,
    created_d2: Optional[datetime.datetime] = None,
    created_on: Optional[datetime.date] = None,
    observed_on: Optional[datetime.date] = None,
    updated_since: Optional[datetime.datetime] = None,

    lat: Optional[float] = None,
    lng: Optional[float] = None,
    radius: Optional[float] = None,
    nelat: Optional[float] = None,
    nelng: Optional[float] = None,
    swlat: Optional[float] = None,
    swlng: Optional[float] = None,

    acc_above: Optional[float] = None,
    acc_below: Optional[float] = None,
    acc_below_or_unknown: Optional[float] = None,

    term_id: Optional[Sequence[int]] = None,
    term_value_id: Optional[Sequence[int]] = None,
    without_term_id: Optional[Sequence[int]] = None,
    without_term_value_id: Optional[Sequence[int]] = None,
    term_id_or_unknown: Optional[Sequence[int]] = None,
    annotation_user_id: Optional[Sequence[int]] = None,

    identifications: Optional[IdentificationFilter] = None,
    quality_grade: Optional[Sequence[QualityGrade]] = None,

    cs: Optional[str] = None,
    csa: Optional[str] = None,
    csi: Optional[Sequence[IUCNStatus]] = None,

    geoprivacy: Optional[Sequence[Geoprivacy]] = None,
    taxon_geoprivacy: Optional[Sequence[Geoprivacy]] = None,
    obscuration: Optional[Sequence[Obscuration]] = None,

    q: Optional[str] = None,
    search_on: Optional[str] = None,

    page: Optional[int] = None,
    per_page: Optional[int] = None,
    order: Optional[Order] = "desc",
    order_by: Optional[OrderBy] = "geo_score",
    only_id: Optional[bool] = None,

    locale: Optional[str] = None,
    preferred_place_id: Optional[int] = None,
    ttl: Optional[int] = None,

    timeout: float = 10.0,
) -> Dict[str, Any]:

    params: Dict[str, str] = {}

    def add(name: str, value: Any) -> None:
        s = _serialize(value)
        if s is not None:
            params[name] = s

    for key, value in locals().items():
        if key == "timeout":
            continue
        add(key, value)

    response = requests.get(
        "https://api.inaturalist.org/v1/observations",
        params=params,
        timeout=timeout,
    )
    response.raise_for_status()
    return response.json()


if __name__ == "__main__":
    observations = get_observations(
        per_page=5,
        page=1,
        order_by="geo_score",
        license=["cc-by", "cc0"],
        photos=True,
        geo=True,
        iconic_taxa=["Plantae"],
    )
    for obs in observations["results"]:
        print(obs)